### ISSUE TITLE
 Issues Initializing IntegrationStudio on Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by GustavoFranzolin** [wso2/integration-studio#1307]
I am trying to use Integration Studio on Ubuntu 24.04 LTS and I am encountering a problem when initializing the tool. I am very frustrated because I have done everything, including installing the latest webkitgtk on the machine, as well as numerous other actions. Can someone help me with the problem below? It happens when running IntegrationStudio.

**Command executed**: ./IntegrationStudio

**Impacts**: Various bugs causing the application to crash, as well as failing to open some project files.

**Output logs**:

```
OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=512m; support was removed in 8.0
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SWT Webkit: Warning, You are using an old version of webkitgtk. (pre 2.4) BrowserFunction functionality will not be avaliable
SWT WebKit: error initializing DBus server, dBusServer == 0
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://product-dist.wso2.com/p2/integration-studio/8.0.0/studio-platform
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:762)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.maximumTimestampInGivenURL(RunUpdaterRootJob.java:149)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdateAvailability(RunUpdaterRootJob.java:89)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdatesAvailable(RunUpdaterRootJob.java:78)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.run(RunUpdaterRootJob.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://product-dist.wso2.com/p2/integration-studio/8.0.0/esb-tools
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:762)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.maximumTimestampInGivenURL(RunUpdaterRootJob.java:149)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdateAvailability(RunUpdaterRootJob.java:96)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdatesAvailable(RunUpdaterRootJob.java:78)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.run(RunUpdaterRootJob.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://product-dist.wso2.com/p2/integration-studio/8.0.0/dss-tools
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:762)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.maximumTimestampInGivenURL(RunUpdaterRootJob.java:149)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdateAvailability(RunUpdaterRootJob.java:103)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdatesAvailable(RunUpdaterRootJob.java:78)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.run(RunUpdaterRootJob.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=403, URL=https://product-dist.wso2.com/p2/integration-studio/8.0.0/bps-tools
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:762)
	at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
	at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
	at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.maximumTimestampInGivenURL(RunUpdaterRootJob.java:149)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdateAvailability(RunUpdaterRootJob.java:110)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdatesAvailable(RunUpdaterRootJob.java:78)
	at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.run(RunUpdaterRootJob.java:71)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```
Thanks

Gustavo F

**Comment by GustavoFranzolin** [comment]
?????????????????

?????????????????

?????????????????

**Comment by ThijsFTW** [comment]
Not a solution but you could try using the new Visual Studio Code plugin instead: https://marketplace.visualstudio.com/items?itemName=WSO2.micro-integrator

**Comment by GustavoFranzolin** [comment]
ThijsFTW, is there any estimated time for WSO2 to fix this major issue? This is a blocker for using the tool for everyone using Ubuntu 24.04.

**Comment by ThijsFTW** [comment]
I don't know. I'm not even sure if it's a WSO2 problem or a problem in your dev environment. See the warning in the startup: _Warning, You are using an old version of webkitgtk. (pre 2.4)_. You might not have installed the latest version because te latest version isn't available in your package manager or IntegrationStudio looks into it's own folders to check for the webkitgtk library? The 403 you receive could also be a sign that you have issues with your network. I can't really help with resolving this for you, sorry. I do recognize working with IntegrationStudio can be painful. The VSCode plugin should be more stable.

**Comment by GustavoFranzolin** [comment]
ThijsFTW, I have already spent a lot of time on this problem. The webkitgtk libraries in Ubuntu 24 are all updated, but the issue is that when running the tool, it looks for a graphical interface class that only exists in the older version of webkit. I imagine anyone trying to install the integration studio on Ubuntu 24.04 will have the same problem, but it really needs confirmation. It's complicated :/"

**Comment by focafunk** [comment]
I have exactly the same error after installing 24.04. Please we do need and Urgent solution to this we are not able to keep on developing!

**Comment by GustavoFranzolin** [comment]
@focafunk, It seems that the WSO2 team is concerned with releasing new versions instead of fixing critical bugs in the latest versions.
Unfortunate :/

**Comment by GustavoFranzolin** [comment]
This problem is causing me terrible consequences, I am using 3 different IDEs to be able to continue the project. The delivery time has increased exponentially.

**Comment by GustavoFranzolin** [comment]
up @SanojPunchihewa

**Comment by SanojPunchihewa** [comment]
Hi @GustavoFranzolin,

The `403` error when trying to update the Studio was fixed sometimes back in the latest version (8.3.0). However as per the shared logs, it seems you are using Integration Studio 8.0.0. Regarding the `webkitgtk` library issues, are you using the Integration Studio 8.3.0 version there?

**Comment by GustavoFranzolin** [comment]
Hi @SanojPunchihewa 

Thank you for your response.

The webkit issue occurs in all versions of the IDE. I have tested them all, including version 8.3.0.

I have the latest webkit version on my Ubuntu 24.04, and I’ve tried many alternatives to fix this problem, but I haven’t been able to solve it so far.

If you could assist me, I believe this issue affects everyone using Ubuntu 24. Thank you!

**Comment by GustavoFranzolin** [comment]
![image](https://github.com/user-attachments/assets/869fcda1-2ef1-461b-8018-f6273dd0ab9d)

**Comment by focafunk** [comment]
Any updates on this? Please we do need your help!

**Comment by GustavoFranzolin** [comment]
@arunans23 , could you help?

**Comment by focafunk** [comment]
@GustavoFranzolin finally I have found out how to solve it after days of research within forums....

First, I have installed manually  libwebkit2gtk-4 as it does not come anymore with the latest ubuntu 24.04

```
sudo add-apt-repository deb http://gb.archive.ubuntu.com/ubuntu jammy main
sudo apt update
sudo apt install libwebkit2gtk-4.0-dev
```

After this, you will have to create manually this folder, otherwise a core dump raises (it is a known bug for eclipse)

`sudo mkdir /tmp/SWT-GDBusServer
`
Finally, I was not able to open my previous workspace, so I had to recreate it from the scratch, and it sems to be working now.

Hope it helps!
Un saludo!

Rodolfo

**Comment by GustavoFranzolin** [comment]
@focafunk, my friend.

I did what you said, and here are the following scenarios: versions 8.2.0 and 8.3.0 have completely stopped now, lol. Every time I try to run it, a log file hs_err_pid_xxxx.log is generated.

However, version 8.0.0 now works correctly without the reported issues! This has helped me a lot.

Thank you very much!

Regards!

Gustavo.

**Comment by focafunk** [comment]
I am running version 8.2.0, In the beginning I had the same problem... a hs_err_pid_xxxx.log was generated, until I found the sudo mkdir /tmp/SWT-GDBusServer workaround, and stopped trying to reuse my previous workspace and created one from the scratch.

Try those steps, but I am happy to hear that at least version 8.0.0 is now working.

BTW, In this thread @ThijsFTW proposed to use the Micro Integrator plugin for visual studio. It does not work, and hangs other plugins, that is why I was forced to keep trying to make Integration Studio work no matter what.

Un saludo!

**Comment by GustavoFranzolin** [comment]
Did you create the folder below and a new workspace, and it worked for you, right?

![image](https://github.com/user-attachments/assets/d2ed5afc-44ec-4d09-b7a7-2516f7c56412)

Unfortunately, it didn't work for me here.

But thanks for the help!

**Comment by rosensilva** [comment]
Hi @GustavoFranzolin,

I resolved the issue based on @focafunk's findings. The problem is with sudo; remove it and create the temporary file using the command `mkdir /tmp/SWT-GDBusServer`.

**Comment by focafunk** [comment]
Also verify that you have the needed permissions. I would do a 
`sudo chmod 777  /tmp/SWT-GDBusServer -R 
`and check again
