### ISSUE TITLE
Unable to run a hello world service while the Micro Integrator  server crashed.

### ISSUE THREAD

**Issue by huanghongqing** [wso2/integration-studio#309]
**Description:**
Add a hello world service and select "Export project atrifacts & run",the Micro Integrator crash

**Affected Product Version:**
WSO2-Integration-Studio-7.0.0-linux-gtk-x86_64
**OS, DB, other environment details and versions:**    
os: Manjaro kde,linux 4.19.91-1
java vm:
openjdk version "1.8.0_232"

**Steps to reproduce:**
At welcome page ,select "hello world service ",and  Right click on the respective Composite Application project and select Export project atrifacts & run from menu.

then we got the error as below:
`[2020-01-09 20:16:52,956]  WARN {org.wso2.micro.integrator.management.apis.ManagementInternalApi} - Micro Integrator Management REST API is enabled
[2020-01-09 20:16:54,256] FATAL {org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager} - Exception encountered in the HTTP Listener. No more connections will be accepted by this transport org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:357)
	at org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager$1.run(PassThroughListeningIOReactorManager.java:536)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onClosed(MultiListenerServerIODispatch.java:63)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onClosed(MultiListenerServerIODispatch.java:32)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.disconnected(AbstractIODispatch.java:100)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionClosed(BaseIOReactor.java:271)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processClosedSessions(AbstractIOReactor.java:439)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.hardShutdown(AbstractIOReactor.java:575)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:306)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	... 1 more`

**Comment by LeonardVertighel** [comment]
I have the same problem but with recent version of the product and the openjdk, and i do not have the Management REST API enabled.

**Description**:
each project i try to execute with the menu "Export project atrifacts & run", the micro integrator crash

**Affected Product Version**:
WSO2-Integration-Studio-7.2.0-linux-gtk-x86_64
**OS, DB, other environment details and versions**:
os: Manjaro lxqt, linux 5.9.16-1
java vm:
openjdk version "11.0.10"

```
[2021-03-04 08:33:08,375]  INFO {EventAdminConfigurationNotifier} - Logging configuration changed. (Event Admin service unavailable - no notification sent).
[2021-03-04 08:33:17,584]  INFO {API} - {api:HelloWorld} Initializing API: HelloWorld
[2021-03-04 08:33:17,594]  INFO {APIDeployer} - API named 'HelloWorld' has been deployed from file : /home/odin/Software/IntegrationStudio/runtime/microesb/tmp/carbonapps/-1234/1614843197531TestCompositeApplication_1.0.0.car/HelloWorld_1.0.0/HelloWorld-1.0.0.xml
[2021-03-04 08:33:17,595]  INFO {CappDeployer} - Successfully Deployed Carbon Application : HelloWorldServiceCompositeExporter_1.0.0{super-tenant}
[2021-03-04 08:33:22,725]  INFO {PassThroughListeningIOReactorManager} - Pass-through HTTP Listener started on 0.0.0.0:8290
[2021-03-04 08:33:27,798]  INFO {PassThroughListeningIOReactorManager} - Pass-through HTTPS Listener started on 0.0.0.0:8253
[2021-03-04 08:33:27,806]  INFO {StartupFinalizer} - WSO2 Micro Integrator started in 29.48 seconds
[2021-03-04 08:33:29,766] FATAL {PassThroughListeningIOReactorManager} - Exception encountered in the HTTP Listener. No more connections will be accepted by this transport org.apache.http.nio.reactor.IOReactorException: I/O dispatch worker terminated abnormally
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:357)
	at org.apache.synapse.transport.passthru.core.PassThroughListeningIOReactorManager$1.run(PassThroughListeningIOReactorManager.java:560)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onClosed(MultiListenerServerIODispatch.java:63)
	at org.apache.synapse.transport.passthru.core.MultiListenerServerIODispatch.onClosed(MultiListenerServerIODispatch.java:32)
	at org.apache.http.impl.nio.reactor.AbstractIODispatch.disconnected(AbstractIODispatch.java:100)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.sessionClosed(BaseIOReactor.java:271)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.processClosedSessions(AbstractIOReactor.java:439)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.hardShutdown(AbstractIOReactor.java:575)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:306)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:105)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:586)
	... 1 more

[2021-03-04 08:33:29,773]  INFO {PassThroughListeningIOReactorManager} - HTTP Listener shutdown.
[2021-03-04 08:33:29,774]  INFO {PassThroughListeningIOReactorManager} - Shutting down shared IO Reactor
[2021-03-04 08:33:33,276]  INFO {PassThroughListeningIOReactorManager} - Pass-through EI_INTERNAL_HTTP_INBOUND_ENDPOINT Listener started on 0.0.0.0:9201
[2021-03-04 08:33:38,377]  INFO {PassThroughListeningIOReactorManager} - Pass-through EI_INTERNAL_HTTPS_INBOUND_ENDPOINT Listener started on 0.0.0.0:9164
Carbon Server WSO2 Enterprise Micro Integrator 1.2.0 at localhost is shutting down...
Carbon Server WSO2 Enterprise Micro Integrator 1.2.0 at localhost has shut down...

```

**Comment by rosensilva** [comment]
Unable to reproduce
