### ISSUE TITLE
Connector schema rendering does not show default values and set values for combo boxes and text boxes

### ISSUE THREAD

**Issue by abeykoon** [wso2/integration-studio#76]
**Description:**

$Subject. This affects usability of connectors as users does not know what the default values are. 

![image](https://user-images.githubusercontent.com/4967046/97457535-da4d0400-195f-11eb-9671-0fd1651f8f00.png)

Schema

```
{
  "connectorName": "file",
  "connectionName": "FTP",
  "title": "FTP Connection Config",
  "help": "<h1>File Connector</h1> <b>The file connector supports Local, FTP, FTPS and SFTP protocols for handling files</b>",
  "elements": [
    {
      "type": "attribute",
      "value": {
        "name": "connectionName",
        "displayName": "Connection Name",
        "inputType": "string",
        "defaultValue": "FILE_CONNECTION_1",
        "required": "true",
        "helpTip": "The name for the file connection",
        "validation": "nameWithoutSpecialCharactors"
      }
    },
    {
      "type": "attributeGroup",
      "value": {
        "groupName": "General",
        "elements": [
          {
            "type": "attributeGroup",
            "value": {
              "groupName": "Basic",
              "elements": [
                {
                  "type": "attribute",
                  "value": {
                    "name": "host",
                    "displayName": "Host",
                    "inputType": "string",
                    "defaultValue": "",
                    "required": "true",
                    "helpTip": "Host name of the FTP server"
                  }
                },
                {
                  "type": "attribute",
                  "value": {
                    "name": "port",
                    "displayName": "Port",
                    "inputType": "string",
                    "defaultValue": "",
                    "required": "true",
                    "helpTip": "The port number of the FTP server"
                  }
                },
                {
                  "type": "attribute",
                  "value": {
                    "name": "username",
                    "displayName": "Username",
                    "inputType": "string",
                    "defaultValue": "",
                    "required": "false",
                    "helpTip": "Username used to connect with the FTP server"
                  }
                },
                {
                  "type": "attribute",
                  "value": {
                    "name": "password",
                    "displayName": "Password",
                    "inputType": "string",
                    "defaultValue": "",
                    "required": "false",
                    "helpTip": "Password to connect with the FTP server"
                  }
                },
                {
                  "type": "attribute",
                  "value": {
                    "name": "userDirIsRoot",
                    "displayName": "User Directory Is Root",
                    "inputType": "booleanOrExpression",
                    "defaultValue": "",
                    "required": "true",
                    "helpTip": "True if user directory is considered as root directory"
                  }
                },
                {
                  "type": "attribute",
                  "value": {
                    "name": "workingDir",
                    "displayName": "Working Directory",
                    "inputType": "string",
                    "defaultValue": "",
                    "required": "true",
                    "helpTip": "Working directory. File paths in operations should be given w.r.t this folder"
                  }
                },
                {
                  "type": "attribute",
                  "value": {
                    "name": "maxFailureRetryCount",
                    "displayName": "Max Failure Retry Count",
                    "inputType": "string",
                    "defaultValue": "0",
                    "required": "false",
                    "helpTip": "Max retry count upon file operation failure"
                  }
                }
              ]
            }
          }
        ]
      }
    },
    {
      "type": "attributeGroup",
      "value": {
        "groupName": "Advanced",
        "elements": [
          {
            "type": "attribute",
            "value": {
              "name": "isPassive",
              "displayName": "Is Passive",
              "inputType": "boolean",
              "defaultValue": "true",
              "required": "false",
              "helpTip":"True if to enter into passive mode"
            }
          },
          {
            "type": "attribute",
            "value": {
              "name": "ftpConnectionTimeout",
              "displayName": "FTP Connection Timeout",
              "inputType": "stringOrExpression",
              "defaultValue": "100000",
              "required": "no",
              "helpTip":"Timeout in milisec for initial control connection"
            }
          },
          {
            "type": "attribute",
            "value": {
              "name": "ftpSocketTimeout",
              "displayName": "FTP Socket Timeout",
              "inputType": "stringOrExpression",
              "defaultValue": "150000",
              "required": "false",
              "helpTip":"Socket timeout for FTP client"
            }
          }
        ]
      }
    }
  ]
}

```

**Comment by abeykoon** [comment]
This affects user experience of the connectors as users think default values are set but actually they are not set. A runtime exception is thrown with file connector for an example. 

```
[2021-03-11 11:43:30,677] ERROR {FileConfig} - {api:TeatAPI} [myLocalFileConn]Failed to initiate file connector configuration. org.wso2.carbon.connector.exception.InvalidConfigurationException: Parameter 'fileLockScheme' contains empty value.
	at org.wso2.carbon.connector.pojo.ConnectionConfiguration.setClusterLockingEnabled(ConnectionConfiguration.java:100)
	at org.wso2.carbon.connector.operations.FileConfig.getConnectionConfigFromContext(FileConfig.java:114)
	at org.wso2.carbon.connector.operations.FileConfig.connect(FileConfig.java:69)
	at org.wso2.carbon.connector.core.AbstractConnector.mediate(AbstractConnector.java:32)
	at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:94)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.template.TemplateMediator.mediate(TemplateMediator.java:136)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:170)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:93)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:141)
	at org.apache.synapse.mediators.template.InvokeMediator.mediate(InvokeMediator.java:93)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:214)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.api.Resource.process(Resource.java:342)
	at org.apache.synapse.api.API.process(API.java:465)
	at org.apache.synapse.api.AbstractApiHandler.apiProcess(AbstractApiHandler.java:93)
	at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:71)
	at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:75)
	at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:67)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:369)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:428)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:182)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
