### ISSUE TITLE
[Integration Studio 8.0.0] 404 when checking for new updates

### ISSUE THREAD

**Issue by wx-yz** [wso2/integration-studio#827]
**Description:**
When checking for new updates UI throws following error

![image](https://user-images.githubusercontent.com/57770159/117868018-efc7b280-b24d-11eb-8e4a-0476e0feb73c.png)

.metadata/.log shows following,

```
!ENTRY org.wso2.integrationstudio.updater 4 0 2021-05-11 11:43:37.549
!MESSAGE Error while connecting to https://product-dist.wso2.com/p2/integration-studio/8.0.0/studio-platform
!STACK 0
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://product-dist.wso2.com/p2/integration-studio/8.0.0/studio-platform
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:762)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
        at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.maximumTimestampInGivenURL(RunUpdaterRootJob.java:149)
        at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdateAvailability(RunUpdaterRootJob.java:89)
        at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdatesAvailable(RunUpdaterRootJob.java:78)
        at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.run(RunUpdaterRootJob.java:71)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

!ENTRY org.wso2.integrationstudio.updater 4 0 2021-05-11 11:43:37.628
!MESSAGE Error while connecting to https://product-dist.wso2.com/p2/integration-studio/8.0.0/esb-tools
!STACK 0
org.jsoup.HttpStatusException: HTTP error fetching URL. Status=404, URL=https://product-dist.wso2.com/p2/integration-studio/8.0.0/esb-tools
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:762)
        at org.jsoup.helper.HttpConnection$Response.execute(HttpConnection.java:707)
        at org.jsoup.helper.HttpConnection.execute(HttpConnection.java:297)
        at org.jsoup.helper.HttpConnection.get(HttpConnection.java:286)
        at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.maximumTimestampInGivenURL(RunUpdaterRootJob.java:149)
        at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdateAvailability(RunUpdaterRootJob.java:96)
        at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.checkUpdatesAvailable(RunUpdaterRootJob.java:78)
        at org.wso2.integrationstudio.updater.handler.RunUpdaterRootJob.run(RunUpdaterRootJob.java:71)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**
8.0.0

**OS, DB, other environment details and versions:**    
Linux

**Comment by rosensilva** [comment]
Hi @wx-yz : this issue was fixed as we have hosted Integration Studio 8.0.0 May update
