### ISSUE TITLE
Can not test Synapse artifacts with secrets using Unit testing framework

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/integration-studio#98]
**Description:**
$subject. When we use the `wso2:vault-look('alias')` Xpath function to fetch the secrets inside a Synapse artifact and test that artifact via the unit testing framework, it will give the following error. 

```
[2020-08-18 02:10:37,381] ERROR {SynapseXPath} - Evaluation of the XPath expression wso2:vault-lookup('token') resulted in an error org.jaxen.UnresolvableException: No Such Function vault-lookup
	at org.jaxen.SimpleFunctionContext.getFunction(SimpleFunctionContext.java:127)
	at org.apache.synapse.util.xpath.SynapseXPathFunctionContext.getFunction(SynapseXPathFunctionContext.java:101)
	at org.jaxen.ContextSupport.getFunction(ContextSupport.java:242)
	at org.jaxen.Context.getFunction(Context.java:216)
	at org.jaxen.expr.DefaultFunctionCallExpr.evaluate(DefaultFunctionCallExpr.java:176)
	at org.jaxen.expr.DefaultXPathExpr.asList(DefaultXPathExpr.java:102)
	at org.jaxen.BaseXPath.selectNodesForContext(BaseXPath.java:675)
	at org.jaxen.BaseXPath.selectNodes(BaseXPath.java:215)
	at org.jaxen.BaseXPath.evaluate(BaseXPath.java:175)
	at org.apache.synapse.util.xpath.SynapseXPath.stringValueOf(SynapseXPath.java:406)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.getArgValues(PayloadFactoryMediator.java:533)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.replace(PayloadFactoryMediator.java:277)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.regexTransform(PayloadFactoryMediator.java:230)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:172)
	at org.apache.synapse.mediators.transform.PayloadFactoryMediator.mediate(PayloadFactoryMediator.java:122)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109)
	at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71)
	at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158)
	at org.apache.synapse.rest.Resource.process(Resource.java:331)
	at org.apache.synapse.rest.API.process(API.java:448)
	at org.apache.synapse.rest.RESTRequestHandler.apiProcess(RESTRequestHandler.java:120)
	at org.apache.synapse.rest.RESTRequestHandler.dispatchToAPI(RESTRequestHandler.java:98)
	at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:71)
	at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:331)
	at org.apache.synapse.core.axis2.SynapseMessageReceiver.receive(SynapseMessageReceiver.java:99)
	at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180)
	at org.apache.synapse.transport.passthru.ServerWorker.processNonEntityEnclosingRESTHandler(ServerWorker.java:367)
	at org.apache.synapse.transport.passthru.ServerWorker.processEntityEnclosingRequest(ServerWorker.java:426)
	at org.apache.synapse.transport.passthru.ServerWorker.run(ServerWorker.java:181)
	at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Sunil-Dutt** [comment]
Any update on this issue?

**Comment by Sunil-Dutt** [comment]
Though the Synapse environment is initialised fine with the XPATH extension function provider initialised at start up 

[2023-07-26 15:15:31,913]  INFO {org.apache.synapse.Axis2SynapseController} - Initializing Synapse at : Wed Jul 26 15:15:31 CEST 2023^M
[2023-07-26 15:15:31,913] DEBUG {org.apache.synapse.Axis2SynapseController} - Initializing Synapse in an already existing axis2 server environment instance^M
[2023-07-26 15:15:32,058]  INFO {org.apache.synapse.core.axis2.Axis2SynapseEnvironment} - Synapse unit testing server enabled^M
[2023-07-26 15:15:32,059]  INFO {org.apache.synapse.unittest.UnitTestingExecutor} - Unit testing agent started^M
[2023-07-26 15:15:32,060]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - Entered to get registered function^M
[2023-07-26 15:15:32,060]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - Entered to get registered function^M
[2023-07-26 15:15:32,061]  INFO {org.apache.synapse.unittest.UnitTestingExecutor} - Synapse unit testing agent has been established on port 9008^M
[2023-07-26 15:15:32,066]  INFO {org.apache.synapse.unittest.UnitTestingExecutor} - Start processing test-case handler^M
[2023-07-26 15:15:32,066]  INFO {org.apache.synapse.unittest.UnitTestingExecutor} - Unit testing agent checks transport Pass-through HTTP Listener port^M
[2023-07-26 15:15:32,070]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - Came to extractProviders  propValue = org.wso2.micro.integrator.mediation.security.vault.xpath.SecureVaultLookupXPathFunctionProviderextProviders = [] is Custom logic true^M
[2023-07-26 15:15:32,070]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - Checking for observerNames [Ljava.lang.String;@1738659e^M
[2023-07-26 15:15:32,070]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - Checking for - observer org.wso2.micro.integrator.mediation.security.vault.xpath.SecureVaultLookupXPathFunctionProvider^M
[2023-07-26 15:15:32,088]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - extractProviders got - org.wso2.micro.integrator.mediation.security.vault.xpath.SecureVaultLookupXPathFunctionProvider@20e4bf84^M
[2023-07-26 15:15:32,088]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - extProviders that were retrieved are [org.wso2.micro.integrator.mediation.security.vault.xpath.SecureVaultLookupXPathFunctionProvider@20e4bf84]^M





The axis2 synapse environment does not have the extension provider when the test case is executed and hence the error

[2023-07-26 15:04:01,888] DEBUG {org.apache.synapse.mediators.builtin.PropertyMediator} - {api:xxxxxx} Start : Property mediator^M
[2023-07-26 15:04:01,894]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - Entering getFunctionContext with prefix = wso2localName = vault-lookupnamespaceURI = null^M
[2023-07-26 15:04:01,894]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - The environment exists org.apache.synapse.core.axis2.Axis2SynapseEnvironment@1feff778^M
[2023-07-26 15:04:01,895]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - The extension provider retrieved from environment  {}^M


Just as a check was able to initialize and then able to use vault-lookup custom XPATH extension function in Unit testing

[2023-07-26 15:04:01,895]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - Entered the method getMatchingExtensionProvider with prefix = wso2localName = vault-lookup^M
[2023-07-26 15:04:01,895]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - Loading observer - org.wso2.micro.integrator.mediation.security.vault.xpath.SecureVaultLookupXPathFunctionProvider^M
[2023-07-26 15:04:01,895]  INFO {org.apache.synapse.util.xpath.ext.XpathExtensionUtil} - Sent the object formedorg.wso2.micro.integrator.mediation.security.vault.xpath.SecureVaultLookupXPathFunctionProvider@2f71f659^M
